language: node_js
node_js:
  - '0.10'
before_install:
  - currentfolder=${PWD##*/}
  - if [ "$currentfolder" != 'generator-bb-project' ]; then cd .. && eval "mv $currentfolder generator-bb-project" && cd generator-bb-project; fi
  - npm install -g grunt-cli
